apiVersion: apps/v1
kind: Deployment
metadata:
  name: sassy-backend
  namespace: sassy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sassy-backend
  template:
    metadata:
      labels:
        app: sassy-backend
    spec:
      initContainers:
      - name: setup-sassy-backend
        # ideally this wouldn't need to be the same image as the main application,
        # but it's got everything we need and easy enough to just re-use
        image: $BACKEND_IMAGE_NAME
        command:
        - /bin/sh
        - -c
        - |
          # set up the migrations in the database
          python manage.py migrate
          # we don't currently need any superusers, so just skip this for now
          #DJANGO_SUPERUSER_PASSWORD=$SUPERUSER_PASSWORD_REPLACE DJANGO_SUPERUSER_USERNAME=$SUPERUSER_USERNAME_REPLACE DJANGO_SUPERUSER_EMAIL=admin@example.com python manage.py createsuperuser --noinput
        envFrom:
        - configMapRef:
            name: backend-configmap
      - name: db-seed
        image: $BACKEND_DB_SEED_IMAGE_NAME
        envFrom:
        - configMapRef:
            name: backend-configmap
      containers:
      - name: sassy-backend
        # at some point, we'll wire up Argo so that this gets explicitly updated with a specific tag
        image: $BACKEND_IMAGE_NAME
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: backend-configmap