apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sassy
  region: eu-west-1

iam:
  withOIDC: true

nodeGroups:
  - name: ng-1
    instanceType: t3.small
    desiredCapacity: 2
    volumeSize: 20
    volumeEncrypted: true
