apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: sassy
  labels:
    type: aws-ebs
spec:
  storageClassName: aws-ebs
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: $EBS_VOLUME_ID
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: sassy
spec:
  storageClassName: aws-ebs
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: aws-ebs